spring.application.name=demo
management.endpoints.web.exposure.include=health,info,beans,mappings
management.info.env.enabled=true
info.app.name=My super cool app
info.app.description= A crazy and fun app. yay
info.app.version=1.0.0

# Spring security Configuration

spring.security.user.name=rain
spring.security.user.password=123
